language: zh
pipeline:
- name: SpacyNLP
  model: zh_core_web_md
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 300
- name: FallbackClassifier
  threshold: 0.6
  ambiguity_threshold: 0.2
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 200
  constrain_similarities: true
- name: RulePolicy
  core_fallback_threshold: 0.6
  core_fallback_action_name: action_default_fallback
  enable_fallback_prediction: true
